### ISSUE TITLE
How to set cookie for specific domain

### ISSUE THREAD

**Issue by TarnjeetSomal** [7leads/ngx-cookie-service#13]
I am trying to set cookie for a domain but its not working. Here is my code: 
`this.cookieService.set('merchant_data', cookieData, expire, '/', 'abc.example.com');`

its  not working but when I remove  domain it works ,  how can I set it for domain ?

**Comment by dhananjaykumar880** [comment]
I am also facing same problem

**Comment by CunningFatalist** [comment]
Hello!

This seems to be an issue more and more people are experiencing. I do not know the specifics of your problem, but I would like to point you to some resources that might help you:

- https://stackoverflow.com/questions/6761415/how-to-set-a-cookie-for-another-domain
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie 

As I see it, it's probably an integration problem and has nothing to do with our package. If you are still facing trouble, you should open a StackOverflow issue. If it is indeed a problem with `ngx-cookie-service`, feel free to come back and open a more specific issue / bug report so that we can fix the package for everyone. 

Cheers from Berlin

**Comment by preservance717** [comment]
@dhananjaykumar880  
Did you solve this problem?

**Comment by caioladislau** [comment]
Did you solve this problem?

**Comment by dhananjaykumar880** [comment]
No, still not working. And somewhere I read some article that we can set a cookie for the different domain as it breaches security policy of browser. So-called banned by browser ;)

**Comment by kumaraditya1999** [comment]
I am also facing the same problem, did anyone find any solution for this yet?

**Comment by CunningFatalist** [comment]
@dhananjaykumar880 @kumaraditya1999 

Reading my comment above, I realize that I did not make this point clear enough. If you check out [the first of the links above](https://stackoverflow.com/questions/6761415/how-to-set-a-cookie-for-another-domain), you will see that **you cannot set cookies for other domains**. [That is also stated in our documentation](https://github.com/7leads/ngx-cookie-service#set-name-string-value-string-expires-number--date-path-string-domain-string-secure-boolean-samesite-lax--strict--void).

**Comment by kumaraditya1999** [comment]
I was migrating my project from angular 4 to angular 8. In the earlier version I was doing so and that was working. Is this thing there in the new update ? Thanks for the time.
