### ISSUE TITLE
Update version dependency/README.md

### ISSUE THREAD

**Issue by Szetty** [7leads/ngx-cookie-service#24]
## Expected Behavior
To import CookieService

## Actual Behavior

Cannot find DOCUMENT from angular/common

## Steps to Reproduce the Problem
Take the specific Angular version: < 4.3.0

## Specifications

  - Version: 4.2.5
  - Browser: -
  - ...

You should update your version dependency/README.md, import DOCUMENT from angular/common works only with Angular version >= 4.3.0

**Comment by paroe** [comment]
Sorry for the late response and thank you for opening this issue.
According to the Git tags of the angular repository `@angular/common` exports `DOCUMENT` since 4.2 ([Github](https://github.com/angular/angular/blob/4.2.x/packages/common/src/common.ts))
We have updated the README and package.json accordingly.
