### ISSUE TITLE
cookie.service.ts is missing from the TypeScript compilation.

### ISSUE THREAD

**Issue by explorerNW** [7leads/ngx-cookie-service#68]
hello author: 
problem:  the file(cookie.service.ts) is actually exist in my node_module fold, but when i run ng serve command ,throw this error "## \node_modules\ngx-cookie-service\cookie-service\cookie.service.ts is missing from the TypeScript compilation."
my env:
Angular CLI: 6.2.9
Node: 10.16.0
OS: win32 x64
Angular: 6.1.10
how can i fix this problem?help...

**Comment by CunningFatalist** [comment]
Hello @explorerNW,

this looks like an integration issue to me. You should try your luck [over at StackOverflow](https://stackoverflow.com/questions/ask). Remember to add actual code to your question, it is very hard to guess what your problem is if you don't. If you find any evidence that this might be an issue with the package itself, feel free to open another issue.

Good luck with your bug hunt!
