### ISSUE TITLE
Get a cookie from a defined path

### ISSUE THREAD

**Issue by blecua84** [7leads/ngx-cookie-service#7]
Hi guys!

Great module! It's very useful!

I have a question for you. I'm going to receive a cookie in my application from an external CRM. It could be stored with path and domain. Using your library, I've tried to retrieve it using the "get" method with cookies's name, but I can't get it if it was created with specified path.

Can I retrieve a cookie specifying the path that was used to create the cookie?

Thanks you in advance!

Jose

**Comment by CunningFatalist** [comment]
Hello,

I am very sorry for the late answer. I am quite busy at the moment and guess that this won't change until the end of the year 😀

Have you managed to solve your issue yet?

I will try to answer your question to the best of my knowledge. It is possible to get cookies from different paths, if you're doing this on the server side. It is more hacky and not recommended, if you're using JavaScript. Sources:

- https://stackoverflow.com/questions/945862/retrieve-a-cookie-from-a-different-path
- https://www.sitepoint.com/community/t/access-cookie-of-different-more-specific-path-but-same-domain/6475/4

I hope this helps.

Cheers


PS: Again, if you solved your issue I would appreciate if you could share your solution here, so that others can use your experience for future reference 👍
